### ISSUE TITLE
Homepage Box linking

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/carbide-probes#10]
As for the two “Over 2,000 Items In Stock & On-Site Fabrication” boxes on the homepage, let’s keep that exact wording in the left box and link the learn more button to our “About” page.

In the right box, can you put this quote “A Satisfied Customer Is the Best Business Strategy Of All” ~Michael LeBoeuf (you can make his name small) and link the learn more button to our Customer Service page.

**Comment by jonathanhauge** [comment]
Request was from Jessica at Carbide.

**Comment by ginfuru** [comment]
@jonathanhauge I added fields for this... but there may be some styling that needs happen.
