### ISSUE TITLE
Measurement Labels

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/carbide-probes#15]
Add measurement labels to length, EWL & Ball diameter in CMM & Ball Gaging.

**Comment by Toddses** [comment]
I am not sure what we're talking about here. Add them to the front end to all CMM Styli categories as well as the two Ball Gaging sub-categories? They appear to have measurement labels already...

**Comment by Toddses** [comment]
@jonathanhauge Is there any more detail on this?

**Comment by jonathanhauge** [comment]
This appears to be resolved. Closing this request.
