### ISSUE TITLE
Related Products

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/carbide-probes#16]
Can related products be disabled yet still have the possibility for them to manually control "up-sells" and have those available instead?

**Comment by Toddses** [comment]
I'll look and see if there's a plugin like this, but if not that will be some significant dev time.

**Comment by jonathanhauge** [comment]
@Toddses I don't know what response this is waiting for as of now. Was a plugin located or will it require dev time? If dev time, could you please provide an estimate?

**Comment by Toddses** [comment]
Okay this functionality already exists on a per product bases. There's a section for 'Linked Products' where you can define up-sells/cross-sells to be displayed on the product's page.
