### ISSUE TITLE
P.O. Number field in Shopping Cart

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/carbide-probes#17]
Can there be a field in the shopping cart that allows the customer to enter a P.O. if they have one?

This field does not need to be mandatory.

**Comment by Toddses** [comment]
So they want the user to be able to enter a second shipping address?

**Comment by jonathanhauge** [comment]
Yes, but that is issue #20. -- Purchase Order (P.O.) entry is a different request.

**Comment by Toddses** [comment]
Oh I thought we were talking about P.O. Boxes.

Can be done, but will take a few hours.

**Comment by ginfuru** [comment]
@Toddses I'll **Estimate** this will take 3 hours

**Comment by Toddses** [comment]
:+1:

**Comment by jonathanhauge** [comment]
Ticket has been approved.
