### ISSUE TITLE
Multiple Shipping Addresses

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/carbide-probes#20]
Can customers save multiple shipping address' to their account? If possible, please build. Ed estimated 2-3 hours. Client has approved.

===

**i.e.** _“a Purchasing Manager is purchasing for multiple factories and would like to have the parts shipped to each individual factory.”_

**Comment by Toddses** [comment]
@ginfuru Hey did you want to buy that plugin from WooThemes for this?

**Comment by Toddses** [comment]
plugin installed
