### ISSUE TITLE
Add Google Analytics Code

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/carbide-probes#3]
Add Google Analytics code to the new website prior to launch.

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-26171803-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by ginfuru** [comment]
@jonathanhauge Could you find out what Carbide's local IP is??

ask them to Google `Whats my IP`

**Comment by ginfuru** [comment]
@jonathanhauge Since I don't have the correct permission sets to add new filters to Carbide's GA account, you'll need to add two excluding filters:

Exclude - `66.195.171.130`
Exclude - `whatever Carbides IP is`
