### ISSUE TITLE
Parts Missing Main Images

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/carbide-probes#32]
There is a significant number of parts that are missing the main images that were loaded into the build environment. I've attached two screenshots for comparison.

![screen shot 2015-10-07 at 3 35 27 pm](https://cloud.githubusercontent.com/assets/12190207/10348817/6540c668-6d09-11e5-9474-4ce7ddc87c6d.png)
![screen shot 2015-10-07 at 3 35 46 pm](https://cloud.githubusercontent.com/assets/12190207/10348818/6541e728-6d09-11e5-8166-d22cd293a0d1.png)

**Comment by Toddses** [comment]
I can take a look in a bit. Not sure what it could be. I literally just transferred the database and all the uploads and didn't change a thing.

**Comment by Toddses** [comment]
This has to do with them naming files like

```
101-100R.jpg
101-100r.jpg
101-062R.jpg
101-062r.jpg
```

When I pull down the uploads, it is not seeing those as different files, and as such is only downloading one of the files (the lowercase r file). I will look into getting scp to get all the files, but this boils down to them not using semantic filenames.

**Comment by ginfuru** [comment]
I also rebuilt images because of the SSL

I've already started exactly what you mentioned.

**Comment by Toddses** [comment]
I wonder if their best bet is to just go through and re-add the images to the affected products, renaming the schematic images to something like `101-062r-schematic.jpg`. I know there's a bunch, but this is going to also cause problems in the future. Possibly taking a back up will not get these repeat images. Any other work that requires a rebuild of the images will not get the repeat images. We are having issues just downloading and uploading the images. They're shooting themselves in the foot here.

**Comment by ginfuru** [comment]
I agree on the future issues. 

We should do an audit of which images are broken and provide a list to Carbide?

**Comment by Toddses** [comment]
we could. its easy enough to see which are broken just by browsing the catalog. if you like i can do the leg work here.

**Comment by ginfuru** [comment]
@Toddses Go ahead and ID the parts. 
@jonathanhauge  I'm going to assign this to you to communicate to the client that they will need to re-upload the list that Todd will provide.

**Comment by Toddses** [comment]
For the record, we aren't seeing this on every `R` product because the schematic was uploaded during a different month than the product image - so they are stored in different directories and those files are repeated.
