### ISSUE TITLE
Font Consistancy Issue

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/carbide-probes#34]
There is discrepancy in what fonts are displayed at various points throughout the website depending on which browser it is being viewed by.

Screenshots from Greg at Carbide are attached.

![after](https://cloud.githubusercontent.com/assets/12190207/10397473/e35e2bd6-6e75-11e5-8030-968afb4703be.jpg)
![before](https://cloud.githubusercontent.com/assets/12190207/10397472/e35dddd4-6e75-11e5-82d7-b56cf5846e15.jpg)

**Comment by Toddses** [comment]
What browser is the 2nd shot from? What version? Is that the only browser with the issue?

**Comment by jonathanhauge** [comment]
2nd shot is from Microsoft Edge browser on a Surface Pro I believe. I'm also seeing that issue with Safari on my iPhone 6.

**Comment by jonathanhauge** [comment]
![img_4111](https://cloud.githubusercontent.com/assets/12190207/10398079/0d10e916-6e79-11e5-8043-840220142a0e.PNG)

**Comment by Toddses** [comment]
I don't see the issue on Jacque's iPhone 6. Ed doesn't either, on the real deal or an emulator. Might be an issue with downloading the font or a cache issue. I believe the font is coming from google CDN.

**Comment by ginfuru** [comment]
I think this was an issue in the Google Font API
