### ISSUE TITLE
Add Unit of Measure Filter

### ISSUE THREAD

**Issue by Toddses** [RainyDayMedia/carbide-probes#39]
On this one, they have already created the product attribute. They may have tried to add the filter to the product page and they found there were no results, or nothing in the drop down. This is because they didn't actually give any products this attribute.

So the real task here is to write a script to fill in those unit of measure attributes. That should prevent them from having to go through each product and adding the attribute.

**Comment by Toddses** [comment]
@jonathanhauge Are they able to do a dump of the parts that includes the unit of measure information? This would be the simplest, fastest, most effective solution.

If not, we can write a script to add this information to each part. It isn't ideal because it takes time (ie. costs more money). That said, to go down this path, I need to verify the following..

* All parts in the CMM Styli category should be `mm`
* All parts in the Ball Gaging Surface-Metric category should be `mm`
* ALL OTHER PARTS should be `in`

Many thanks.

**Comment by Toddses** [comment]
@jonathanhauge is this something they're still interested in?

**Comment by ginfuru** [comment]
@jonathanhauge - Closing this issue since there has been no movement in two months.
