### ISSUE TITLE
Exclude IPs in Analytics

### ISSUE THREAD

**Issue by ginfuru** [RainyDayMedia/carbide-probes#4]
@jonathanhauge  
Since I don't have the correct permission sets to add new filters to Carbide's GA account, you'll need to add two excluding filters:

Exclude - `66.195.171.130`
Exclude - `whatever Carbides IP is`

**Comment by jonathanhauge** [comment]
@ginfuru On it. I've excluded our office and sent the request to Carbide for their IP address.

**Comment by jonathanhauge** [comment]
Carbide's office has been excluded. This is complete.
