### ISSUE TITLE
Split Part Number and Model Numbers

### ISSUE THREAD

**Issue by ginfuru** [RainyDayMedia/carbide-probes#42]
@Toddses When you get back go ahead and do this... be sure to track you time under RDM internal. Since the project budget is shot. 

#### Need to be separated:

- [x]  Manf. Part Number should a separate Attribute in WooCommerce
  - [x] Model Number
  - [x] OEM Part number

**Comment by Toddses** [comment]
This is done and has been waiting for approval to move it into production for a couple weeks.. See #25

**Comment by ginfuru** [comment]
@Toddses Thanks I see where you did those updates 

@jonathanhauge Looks likes Todd reached out to you on issue #25 roughly **10 days ago...** Not sure what you have set up for notifications via email or webhooks with slack

**Comment by ginfuru** [comment]
*Related to:* #25
