### ISSUE TITLE
Uploading of New parts

### ISSUE THREAD

**Issue by ginfuru** [RainyDayMedia/carbide-probes#46]
@Toddses  Here are both lists that need to be vetted and uploaded to Carbide: http://rdm.d.pr/18eHI

@jonathanhauge I need to know where this time is tracked... *Pretty important for us to be on the same page as Baldwin.*

**Comment by Toddses** [comment]
@jonathanhauge Okay the parts have been imported to the production site. As requested, they are all set to draft so they won't appear in the store until they are published.
