### ISSUE TITLE
Categories Question

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/carbide-probes#49]
Is it possible to have specific dropdown options per category selected?

Is there a place that we could add the schematic for the category based on what category is selected to help guide people through the dropdown options?

**Comment by Toddses** [comment]
Pretty sure we already did this and then it was never used. Let me look into it.

**Comment by Toddses** [comment]
This is two separate issues. Splitting and closing this one.

**Comment by jonathanhauge** [comment]
Thanks @Toddses
