### ISSUE TITLE
Change Widget Dropdowns based on selected category.

### ISSUE THREAD

**Issue by Toddses** [RainyDayMedia/carbide-probes#54]
Is it possible to have specific dropdown options per category selected?

**Comment by Toddses** [comment]
I don't think this is going to be trivial. Its not something I've seen built in before. We can definitely look for a plugin and we might get lucky.

Otherwise I would expect some significant dev time.

**Comment by ginfuru** [comment]
@toddses  The solution to keep the costs down is to use the filter product categories widget with additional widget areas.  I'll work on this tonight/tomorrow *(12/31)*  Just a lot of copying of the attribute filters

**Comment by ginfuru** [comment]
@jonathanhauge I went ahead and tracked my time on this... it was roughly 1.75 hours - the time logs are marked for 1/4/16 to keep/stay inside of the maintenance agreement of 5 hours.

**Comment by jonathanhauge** [comment]
Thanks Ed!


Jonathan Hauge
Project Manager, Baldwin Creative & Co.
937-490-4005
1360 Technology Ct., Suite 300, Beavercreek, OH 45430
baldwincreative.com
<http://www.wbenc.org/>
<https://www.linkedin.com/company/baldwin-creative-&-company>
<https://www.facebook.com/BaldwinCreative>
<https://twitter.com/BaldwinCreative>

Confidentiality Notice: This email message, including any attachments, is
for the sole use of the intended recipient(s) and may contain confidential
and privileged information. Any unauthorized review, use, disclosure or
distribution is prohibited. If you are not the intended recipient, please
contact the sender by reply e-mail and destroy all copies of the original
message.
