### ISSUE TITLE
SagePay Giving Errors

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/carbide-probes#55]
Sage pay is currently not working on their website.
They have had two customers try to check out and their credit cards will not process.
 
The client did a test order this morning and also received the error.  When you hit the “pay securely with Sage” button after entering in the credit card information, a message pops up at the top of the page that states internal error.

**Comment by ginfuru** [comment]
error is in relation to OpenSSL being out of date on the server... which SagePay does not like. 
**Solution:** Updated OpenSSL
