### ISSUE TITLE
Upload Data file

### ISSUE THREAD

**Issue by ginfuru** [RainyDayMedia/carbide-probes#57]
new unit of measurement 

related to #39

file is located here: http://rdm.d.pr/xOAi

**Comment by Toddses** [comment]
@jonathanhauge this is ready and live. pretty low impact. based on the data dump, product detail pages will now show the appropriate unit of measurement and conversion. currently only supports `in` or `mm` in any unit of measure field.

I also updated plugins and WP core to latest versions. Only patch releases so should be fairly low impact as well.
