### ISSUE TITLE
Transfer Licenses

### ISSUE THREAD

**Issue by Toddses** [RainyDayMedia/carbide-probes#6]
@ginfuru @jonathanhauge 

Need to transfer the licenses from staging for WooCommerce UPS Shipping and WooCommerce SagePay plugins to the production site.

DO NOT update these plugins at the moment. We will need to include updating these two plugins in our first round of maintenance.

**Comment by ginfuru** [comment]
@Toddses 
* Deactivated the UPS Shipping Module for **_Build_** 
* SagePay was updated to US version so it was not activated.
