### ISSUE TITLE
Place Webmaster Tools script.

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/carbide-probes#7]
Please place in site for verification upon launch.

<meta name="google-site-verification" content="w9XRIdvzpCmnopRTL0JF54onMF27aTFuWxQzM1QuPFo" />

**Comment by jonathanhauge** [comment]
<meta name="google-site-verification" content="w9XRIdvzpCmnopRTL0JF54onMF27aTFuWxQzM1QuPFo" />

**Comment by ginfuru** [comment]
@jonathanhauge if you place the info for contents into **_WordPress SEO_** you'll verify the site.
