### ISSUE TITLE
Payment Processing Error

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/carbide-probes#8]
"I just tried placing a credit card order on the website and it didn’t take me to the credit card payment screen.  An error message came up."

I would like to process an order all the way through so I can see how the order comes through on our end and through the credit card website.

**Comment by Toddses** [comment]
Looks like this is because SagePay isn't set up. I'll fill in the settings and give it another go.

**Comment by Toddses** [comment]
@jonathanhauge Assigning this to you for follow up info.

I don't think we ever got their SagePay info. I found an M_ID and M_Key but these don't seem to match up with what is required by the WooCommerce settings. What we need is a Vendor Name, the Vendor Email address, and the Encryption Passwords (in particular the LIVE password - tho it would be good to have the Test and Simulation passwords as well).

**Comment by Toddses** [comment]
I've installed sage pay USA. We need confirmation on their Merchant ID and Key.
